# Config file for automatic testing at travis-ci.org
language: python
python:
  - "3.5"
  - "3.4"
  - "3.3"
  - "2.7"
  - "2.6"
  - "pypy"
  - "pypy3"
matrix:
  include:
    - python: 2.7
      env: TESTENV=docs
  exclude:
    - python: 2.6
    - python: 3.3
    - python: 3.4
    - python: 3.5
addons:
  apt:
    packages:
    - python-numpy
    - gfortran
# Command to install dependencies on Travis environment
install: pip install -r requirements_dev.txt
# Command to run tests, e.g. python setup.py test
script:
  - if [[ "$TESTENV" != "docs" ]]; then
      python setup.py test;
    else
      cd docs && sphinx-build -W -T -b html . ../html;
    fi
